AllCops:
  TargetRubyVersion: 2.4.0
  Exclude:
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Rails:
  Enabled: true

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleAlignWith, SupportedStylesAlignWith, AutoCorrect.
# SupportedStylesAlignWith: keyword, variable, start_of_line
Lint/EndAlignment:
  Exclude:
    - 'node_modules/rails-erb-loader/erb_transformer.rb'

# Offense count: 23
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 130

# Offense count: 1
Security/Eval:
  Exclude:
    - 'node_modules/rails-erb-loader/erb_transformer.rb'

# Offense count: 2
# Cop supports --auto-correct.
Security/YAMLLoad:
  Exclude:
    - 'bin/webpack'
    - 'bin/webpack-dev-server'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentOneStep, IndentationWidth.
# SupportedStyles: case, end
Style/CaseIndentation:
  Exclude:
    - 'node_modules/rails-erb-loader/erb_transformer.rb'

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

# Offense count: 6
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/home_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/EmptyLines:
  Exclude:
    - 'bin/setup'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: compact, expanded
Style/EmptyMethod:
  Exclude:
    - 'app/controllers/home_controller.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment, ForceEqualSignAlignment.
Style/ExtraSpacing:
  Exclude:
    - 'bin/webpack'

Style/Documentation:
  Enabled: false

# Offense count: 2
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Exclude:
    - 'node_modules/node-sass/src/libsass/extconf.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/LeadingCommentSpace:
  Exclude:
    - 'node_modules/node-sass/src/libsass/extconf.rb'

# Offense count: 4
# Cop supports --auto-correct.
Style/MutableConstant:
  Exclude:
    - 'bin/webpack'
    - 'bin/webpack-dev-server'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/spring.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment.
Style/SpaceAroundOperators:
  Exclude:
    - 'bin/webpack'

# Offense count: 2
# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Exclude:
    - 'config/environments/production.rb'

# Offense count: 36
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'bin/spring'
    - 'bin/webpack'
    - 'bin/webpack-dev-server'
    - 'bin/yarn'
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    - 'node_modules/node-sass/src/libsass/extconf.rb'
    - 'test/application_system_test_case.rb'

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiteralsInInterpolation:
  Exclude:
    - 'bin/webpack'
    - 'bin/webpack-dev-server'
    - 'bin/yarn'
    - 'node_modules/node-sass/src/libsass/extconf.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets
