# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b268ffca92cad235244e009434747cc64d14cfdf9db7d647e8553cb89ff0d7de13313b39c382d67e2e501d5760252f5ee14c8647fdb8b5876455d28d19894043

test:
  secret_key_base: 48cf3fc4fac87fc8c830a58b34a0896a50baaaf318aa3cb88b99f27374403dcc67ba1682cbb29dfed8dffa3d59e8bb7a1d15d55f217292ddd9b844db06ec76ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
